# Gene expression dataset (Golub et al.)
## Molecular Classification of Cancer by Gene Expression Monitoring

### Context

This dataset comes from a proof-of-concept study published in 1999 by Golub et al. It showed how new cases of cancer could be classified by gene expression monitoring (via DNA microarray) and thereby provided a general approach for identifying new cancer classes and assigning tumors to known classes. These data were used to classify patients with acute myeloid leukemia (AML) and acute lymphoblastic leukemia (ALL).

### Content

Golub et al "Molecular Classification of Cancer: Class Discovery and Class
Prediction by Gene Expression Monitoring"

There are two datasets containing the initial (training, 38 samples) and independent (test, 34 samples) datasets used in the paper. These datasets contain measurements corresponding to ALL and AML samples from Bone Marrow and Peripheral Blood. Intensity values have been re-scaled such that overall intensities for each chip are equivalent. (Source: https://www.kaggle.com/crawford/gene-expression)

### Acknowledgements

Molecular Classification of Cancer: Class Discovery and Class Prediction by Gene Expression

Science 286:531-537. (1999). Published: 1999.10.14

T.R. Golub, D.K. Slonim, P. Tamayo, C. Huard, M. Gaasenbeek, J.P. Mesirov, H. Coller, M. Loh, J.R. Downing, M.A. Caligiuri, C.D. Bloomfield, and E.S. Lander

These datasets have been converted to a comma separated value files (CSV).

### Inspiration

These datasets are great for classification problems. The original authors used the data to classify the type of cancer in each patient by their gene expressions.

## My approach to analysing this dataset @@@@@@@
After reading [Golub et al](https://science.sciencemag.org/content/286/5439/531)'s paper, I will try to reproduce their findings using different classification algorithms. The authors found 50 informative genes as predictors of ALL/AML cancer type.

@@@@@@@@@@@ explain my goal here

## Exploratory Data Analysis

take a look:
https://www.kaggle.com/nageshsingh/classification-of-cancer # drops 'call' columns!
https://www.kaggle.com/varimp/gene-expression-classification # drops 'call' columns!

In [8]:
import pandas as pd

In [9]:
train_data = pd.read_csv('data_set_ALL_AML_train.csv')
test_data = pd.read_csv('data_set_ALL_AML_independent.csv')

In [10]:
train_data

,Gene Description,Gene Accession Number,1,call,2,call.1,3,call.2,4,call.3,...,29,call.33,30,call.34,31,call.35,32,call.36,33,call.37
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-214,A,-139,A,-76,A,-135,A,...,15,A,-318,A,-32,A,-124,A,-135,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-153,A,-73,A,-49,A,-114,A,...,-114,A,-192,A,-49,A,-79,A,-186,A
2,AFFX-BioB-3_at (endogenous control),AFFX-BioB-3_at,-58,A,-1,A,-307,A,265,A,...,2,A,-95,A,49,A,-37,A,-70,A
3,AFFX-BioC-5_at (endogenous control),AFFX-BioC-5_at,88,A,283,A,309,A,12,A,...,193,A,312,A,230,P,330,A,337,A
4,AFFX-BioC-3_at (endogenous control),AFFX-BioC-3_at,-295,A,-264,A,-376,A,-419,A,...,-51,A,-139,A,-367,A,-188,A,-407,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7124,PTGER3 Prostaglandin E receptor 3 (subtype EP3...,X83863_at,793,A,782,A,1138,A,627,A,...,279,A,737,A,588,A,1170,A,2315,A
7125,HMG2 High-mobility group (nonhistone chromosom...,Z17240_at,329,A,295,A,777,P,170,A,...,51,A,227,A,361,A,284,A,250,A
7126,RB1 Retinoblastoma 1 (including osteosarcoma),L49218_f_at,36,A,11,A,41,A,-50,A,...,6,A,-9,A,-26,A,39,A,-12,A
7127,GB DEF = Glycophorin Sta (type A) exons 3 and ...,M71243_f_at,191,A,76,A,228,A,126,A,...,2484,P,371,A,133,A,298,A,790,P
7128,GB DEF = mRNA (clone 1A7),Z78285_f_at,-37,A,-14,A,-41,A,-91,A,...,-2,A,-31,A,-32,A,-3,A,-10,A

In [16]:
train_data.columns

Index(['Gene Description', 'Gene Accession Number', '1', 'call', '2', 'call.1',
       '3', 'call.2', '4', 'call.3', '5', 'call.4', '6', 'call.5', '7',
       'call.6', '8', 'call.7', '9', 'call.8', '10', 'call.9', '11', 'call.10',
       '12', 'call.11', '13', 'call.12', '14', 'call.13', '15', 'call.14',
       '16', 'call.15', '17', 'call.16', '18', 'call.17', '19', 'call.18',
       '20', 'call.19', '21', 'call.20', '22', 'call.21', '23', 'call.22',
       '24', 'call.23', '25', 'call.24', '26', 'call.25', '27', 'call.26',
       '34', 'call.27', '35', 'call.28', '36', 'call.29', '37', 'call.30',
       '38', 'call.31', '28', 'call.32', '29', 'call.33', '30', 'call.34',
       '31', 'call.35', '32', 'call.36', '33', 'call.37'],
      dtype='object')

In [13]:
train_data.describe()#include='all')

,1,2,3,4,5,6,7,8,9,10,...,35,36,37,38,28,29,30,31,32,33
count,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,...,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000,7129.000000
mean,641.367092,690.246318,698.307897,600.985271,679.532894,564.797728,584.437649,571.359097,789.713705,599.483097,...,514.496704,775.143498,689.248141,626.885959,673.279422,556.463179,718.934493,598.648899,676.920887,723.563473
std,2264.294361,2468.814372,2485.656277,2340.047428,2375.895416,2494.604090,2412.812263,2378.780450,2580.157021,2421.156219,...,2440.722824,2676.664777,2543.537830,2473.180838,2413.149603,2376.681824,2533.678058,2405.268550,2436.964933,2507.382019
min,-19826.000000,-17930.000000,-27182.000000,-23396.000000,-10339.000000,-21658.000000,-24024.000000,-27570.000000,-25171.000000,-12500.000000,...,-16281.000000,-27398.000000,-23673.000000,-23645.000000,-20376.000000,-9501.000000,-17580.000000,-25491.000000,-28400.000000,-27811.000000
25%,-21.000000,-14.000000,-31.000000,-33.000000,8.000000,-26.000000,-33.000000,-58.000000,-14.000000,-15.000000,...,-43.000000,-27.000000,-23.000000,-22.000000,-16.000000,-13.000000,-25.000000,-32.000000,-22.000000,-38.000000
50%,159.000000,130.000000,177.000000,139.000000,146.000000,106.000000,134.000000,140.000000,166.000000,103.000000,...,108.000000,144.000000,134.000000,133.000000,150.000000,82.000000,128.000000,107.000000,155.000000,170.000000
75%,535.000000,488.000000,610.000000,497.000000,471.000000,401.000000,497.000000,527.000000,609.000000,386.000000,...,396.000000,569.000000,505.000000,490.000000,517.000000,309.000000,488.000000,443.000000,549.000000,649.000000
max,31086.000000,29288.000000,28056.000000,31449.000000,29543.000000,38467.000000,41911.000000,40065.000000,23602.000000,28033.000000,...,61228.000000,37164.000000,32204.000000,29169.000000,29833.000000,30354.000000,25055.000000,28350.000000,25093.000000,32946.000000

In [6]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7129 entries, 0 to 7128
Data columns (total 78 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Gene Description       7129 non-null   object
 1   Gene Accession Number  7129 non-null   object
 2   1                      7129 non-null   int64
 3   call                   7129 non-null   object
 4   2                      7129 non-null   int64
 5   call.1                 7129 non-null   object
 6   3                      7129 non-null   int64
 7   call.2                 7129 non-null   object
 8   4                      7129 non-null   int64
 9   call.3                 7129 non-null   object
 10  5                      7129 non-null   int64
 11  call.4                 7129 non-null   object
 12  6                      7129 non-null   int64
 13  call.5                 7129 non-null   object
 14  7                      7129 non-null   int64
 15  call.6                 7129 non-null   object
 16  8                      7129 non-null   int64
 17  call.7                 7129 non-null   object
 18  9                      7129 non-null   int64
 19  call.8                 7129 non-null   object
 20  10                     7129 non-null   int64
 21  call.9                 7129 non-null   object
 22  11                     7129 non-null   int64
 23  call.10                7129 non-null   object
 24  12                     7129 non-null   int64
 25  call.11                7129 non-null   object
 26  13                     7129 non-null   int64
 27  call.12                7129 non-null   object
 28  14                     7129 non-null   int64
 29  call.13                7129 non-null   object
 30  15                     7129 non-null   int64
 31  call.14                7129 non-null   object
 32  16                     7129 non-null   int64
 33  call.15                7129 non-null   object
 34  17                     7129 non-null   int64
 35  call.16                7129 non-null   object
 36  18                     7129 non-null   int64
 37  call.17                7129 non-null   object
 38  19                     7129 non-null   int64
 39  call.18                7129 non-null   object
 40  20                     7129 non-null   int64
 41  call.19                7129 non-null   object
 42  21                     7129 non-null   int64
 43  call.20                7129 non-null   object
 44  22                     7129 non-null   int64
 45  call.21                7129 non-null   object
 46  23                     7129 non-null   int64
 47  call.22                7129 non-null   object
 48  24                     7129 non-null   int64
 49  call.23                7129 non-null   object
 50  25                     7129 non-null   int64
 51  call.24                7129 non-null   object
 52  26                     7129 non-null   int64
 53  call.25                7129 non-null   object
 54  27                     7129 non-null   int64
 55  call.26                7129 non-null   object
 56  34                     7129 non-null   int64
 57  call.27                7129 non-null   object
 58  35                     7129 non-null   int64
 59  call.28                7129 non-null   object
 60  36                     7129 non-null   int64
 61  call.29                7129 non-null   object
 62  37                     7129 non-null   int64
 63  call.30                7129 non-null   object
 64  38                     7129 non-null   int64
 65  call.31                7129 non-null   object
 66  28                     7129 non-null   int64
 67  call.32                7129 non-null   object
 68  29                     7129 non-null   int64
 69  call.33                7129 non-null   object
 70  30                     7129 non-null   int64
 71  call.34                7129 non-null   object
 72  31                     7129 non-null   int64
 73  call.35                7129 non-null   object
 74  32                     7129 non-null   int64
 75  call.36                7129 non-null   object
 76  33                     7129 non-null   int64
 77  call.37                7129 non-null   object
dtypes: int64(38), object(40)
memory usage: 4.2+ MB

In [18]:
train_data['call.2'].unique()

array(['A', 'P', 'M'], dtype=object)

The columns named 'call' have 3 possible values: Present, Absent, and Marginal.
In [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1409797/) the authors explain that the DNA microarray manufacturer Affymetrix uses a non-parametric statistical test (Wilcoxon signed rank test) of whether significantly more perfect matches show more hybridization signal than their corresponding mismatches to produce the detection call (Absent (A), Present (P) or Marginal (M)). Their results show that the use of a threshold fraction of Present detection calls (derived by MAS5) provides a simple method that effectively eliminates from analysis probe sets that are unlikely to be reliable while preserving the most significant probe sets and those turned on or off; it thereby increases the ratio of true positives to false positives.

For these reasons, I will work only with those rows where `'call' == 'P'`

[More information about this here.](https://www.kaggle.com/crawford/gene-expression/discussion/120087)

what is each row? a gene

what is each column? for the ones named with numbers: each column is a patient
                     for the ones named "call.#": how the gene was classified as A, P or M >>> what are these?
                     `train_data['call.2'].unique()`<br>
                     `array(['A', 'P', 'M'], dtype=object)`<br>

I want to keep only 'P' columns


should I reorder the columns?

do I have duplicates?

In [12]:
test_data.columns

Index(['Gene Description', 'Gene Accession Number', '39', 'call', '40',
       'call.1', '42', 'call.2', '47', 'call.3', '48', 'call.4', '49',
       'call.5', '41', 'call.6', '43', 'call.7', '44', 'call.8', '45',
       'call.9', '46', 'call.10', '70', 'call.11', '71', 'call.12', '72',
       'call.13', '68', 'call.14', '69', 'call.15', '67', 'call.16', '55',
       'call.17', '56', 'call.18', '59', 'call.19', '52', 'call.20', '53',
       'call.21', '51', 'call.22', '50', 'call.23', '54', 'call.24', '57',
       'call.25', '58', 'call.26', '60', 'call.27', '61', 'call.28', '65',
       'call.29', '66', 'call.30', '63', 'call.31', '64', 'call.32', '62',
       'call.33'],
      dtype='object')

In [10]:
test_data.head()

,Gene Description,Gene Accession Number,39,call,40,call.1,42,call.2,47,call.3,...,65,call.29,66,call.30,63,call.31,64,call.32,62,call.33
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-342,A,-87,A,22,A,-243,A,...,-62,A,-58,A,-161,A,-48,A,-176,A
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-200,A,-248,A,-153,A,-218,A,...,-198,A,-217,A,-215,A,-531,A,-284,A
2,AFFX-BioB-3_at (endogenous control),AFFX-BioB-3_at,41,A,262,A,17,A,-163,A,...,-5,A,63,A,-46,A,-124,A,-81,A
3,AFFX-BioC-5_at (endogenous control),AFFX-BioC-5_at,328,A,295,A,276,A,182,A,...,141,A,95,A,146,A,431,A,9,A
4,AFFX-BioC-3_at (endogenous control),AFFX-BioC-3_at,-224,A,-226,A,-211,A,-289,A,...,-256,A,-191,A,-172,A,-496,A,-294,A